# Hadolint configuration for Dockerfile linting
# https://github.com/hadolint/hadolint

# DL3008: We don't pin apt package versions because:
# - Package versions change frequently in Debian/Ubuntu repos
# - We want to receive security updates from base image
# - Pinning makes Dockerfile less portable across base image versions
# - Our base image (jenkins/jenkins:lts) is regularly updated
ignored:
  - DL3008

# Set failure threshold - only fail on errors, not warnings
failure-threshold: error

# Trusted registries
trustedRegistries:
  - docker.io
  - jenkins
