# .hadolint.yaml

failure-threshold: error

no-fail: true

ignored:
  - DL3003  # using `cd` instead of WORKDIR is okay in your context
  - DL3006  # image version is not pinned
  - DL3007  # using `latest` is acceptable for this learning project
  - DL3008  # apt install pin versions isn’t required
  - DL3018  # apk add pin versions is okay / not relevant if not using Alpine
  - DL3022  # allow COPY --from (multi-stage builds)
  - DL3025  # allowing shell-notation in RUN
  - DL3028  # gem install without version pin
  - DL3059  # consecutive RUN commands are fine
  - DL4006  # no need for `pipefail` in your scripts
  - SC2016  # you’re okay with single-quoted shell‑script fragments