# .hadolint.yaml

failure-threshold: error

ignored:
  - DL3003  # use WORKDIR instead of cd
  - DL3006  # pin image versions if desired
  - DL3007  # using latest (acceptable in your learning context)
  - DL3008  # pin versions when installing (apt)
  - DL3018  # apk add pin versions (if using Alpine)
  - DL3022  # rule for COPY --from (multi-stage) as you allow it
  - DL3025  # you permit shell/(JSON) notation for RUN
  - DL3028  # gem install pin versions
  - DL3059  # multiple consecutive RUN instructions (you accept)
  - DL4006  # pipefail requirement
  - SC2016  # single-quotes in shell script you accept