# .markdownlint.yaml

default: true

# Customize MD013 (line-length)
MD013:
  line_length: 9999
  heading_line_length: 100
  code_blocks: false

# Allow inline HTML for specific elements
MD033:
  allowed_elements:
    - "details"
    - "summary"
    - "br"
    - "small"

# Allow duplicate headings if nested differently
MD024:
  allow_different_nesting: true