default: true

# Line‑length rule (MD013)
MD013:
  line_length: 9999
  heading_line_length: 100
  code_blocks: false

# Inline HTML allowed for certain elements (MD033)
MD033:
  allowed_elements:
    - "details"
    - "summary"
    - "br"
    - "small"

# Duplicate headings allowed if they are nested differently (MD024)
MD024:
  allow_different_nesting: true